const defaultCampaigns=[
{id:1,title:'Solar Farm Delta',description:'Строительство солнечной электростанции мощностью 5 МВт. Проект обеспечит чистой энергией 3 000 домохозяйств.',goal:10,raised:7.3,daysLeft:12,owner:'0x41AF...C892',status:'active',contributions:[{address:'0xAA3f...1B2c',amount:2,time:'13:05'},{address:'0xFF92...8E4d',amount:1,time:'13:20'},{address:'0xBB01...3A7f',amount:2.3,time:'14:45'},{address:'0xCC54...9D1e',amount:2,time:'16:10'}],dividendHistory:[]},
{id:2,title:'AI Startup Fund',description:'Венчурный фонд для финансирования AI-стартапов на ранней стадии.',goal:15,raised:15,daysLeft:0,owner:'0xA8F2...D631',status:'completed',contributions:[{address:'0xDD23...4C9a',amount:5,time:'09:15'},{address:'0xEE67...2F8b',amount:7,time:'10:30'},{address:'0xFF11...6A3c',amount:3,time:'11:00'}],dividendHistory:[{id:1,date:'10.07.2026',total:100,breakdown:[{name:'0xDD23...4C9a',share:33.3,received:33.3},{name:'0xEE67...2F8b',share:46.7,received:46.7},{name:'0xFF11...6A3c',share:20,received:20}]}]},
{id:3,title:'Green Hydrogen Plant',description:'Завод по производству зелёного водорода с использованием возобновляемой энергии.',goal:25,raised:8.1,daysLeft:31,owner:'0x93CE...B203',status:'active',contributions:[{address:'0xAA3f...1B2c',amount:3,time:'08:40'},{address:'0xBB01...3A7f',amount:5.1,time:'12:00'}],dividendHistory:[]},
{id:4,title:'DeFi Yield Protocol',description:'Протокол автоматизированного управления ликвидностью для максимизации доходности.',goal:8,raised:6.4,daysLeft:7,owner:'0x5FGH...D772',status:'active',contributions:[{address:'0xCC54...9D1e',amount:2,time:'10:20'},{address:'0xDD23...4C9a',amount:4.4,time:'11:55'}],dividendHistory:[]}
];
function campaigns(){let x=localStorage.getItem('campaigns');if(!x){localStorage.setItem('campaigns',JSON.stringify(defaultCampaigns));return defaultCampaigns}return JSON.parse(x)}
function saveCampaigns(x){localStorage.setItem('campaigns',JSON.stringify(x))}
function user(){return JSON.parse(localStorage.getItem('user')||'null')}
function campaignId(){return Number(new URLSearchParams(location.search).get('id')||1)}
function campaign(){return campaigns().find(c=>c.id===campaignId())||campaigns()[0]}
function pct(c){return Math.min(100,Math.round(c.raised/c.goal*100))}
function status(c){return `<span class="status ${c.status==='completed'?'done':''}"><span class="dot"></span>${c.status==='active'?'Активна':'Завершена'}</span>`}
function card(c){return `<article class="card"><div class="between"><h3 class="card-title">${c.title}</h3>${status(c)}</div><p class="muted small">${c.description}</p><div class="progress mt"><span style="width:${pct(c)}%"></span></div><div class="between mt mono small"><span class="green">${pct(c)}%</span><span class="muted">${c.raised} / ${c.goal} ETH</span></div><div class="between mt small"><span class="muted">${c.daysLeft?c.daysLeft+' дней':'Завершён'}</span><a class="green" href="campaign.html?id=${c.id}">Подробнее →</a></div></article>`}
function nav(){const u=user();return `<nav class="navbar"><div class="container nav-inner"><a class="brand" href="index.html"><span class="brand-mark">↗</span>CHAIN<span class="green">FUND</span></a><div class="nav-actions">${u?`<span class="wallet-chip"><span class="dot"></span>${u.address}</span><a class="btn" href="dashboard.html">Личный кабинет</a><button class="btn btn-danger" onclick="logout()">Выйти</button>`:`<button class="btn btn-primary" onclick="location.href='auth.html'">MetaMask</button><a class="btn" href="auth.html">Войти</a>`}</div></div></nav>`}
function logout(){localStorage.removeItem('user');location.href='index.html'}
function mountNav(){document.body.insertAdjacentHTML('afterbegin',nav())}
